name : tests

on: push

jobs:
  JunitTests:
    runs-on: ubuntu-latest
    steps:
      - name: moveToRepository
        uses: actions/checkout@v3
      - name: installJava17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: runMavenTest
        run: mvn test
